// Copyright (c) 2021 Beatrieziz

#define were void
#define no open_rick_roll
#define strangers (
#define to )
#define love {
#define _you std
#define know ::
#define the string
#define rules url
#define And =
#define so " https://bit.ly/39zvNSI"
#define Do ;
#define I system
#define A (
#define full std
#define commitments ::
#define what string
#define im (
#define thinking PROG
#define of )
#define You .
#define wouldnt append
#define get (
#define This url
#define From )
#define any .
#define other c_str
#define guys (
#define _I )
#define just )
#define wanna ;
#define tell }
#define yOu int
#define how main
#define Im (
#define feeling )
#define gotta {
#define make open_rick_roll
#define yoU (
#define understand )
#define never ;
#define gonna return
#define give 0
#define YOU ;
#define up ;
#define let ;
#define down ;
#define run ;
#define around ;
#define aND ;
#define desert ;
#define _make ;
#define cry ;
#define say ;
#define goodbye
#define _tell ;
#define a ;
#define lie ;
#define AND ;
#define hurt ;
#define __you }
